[
  {
    "model": "activities.activity",
    "pk": 1,
    "fields": {
      "created_on": "2025-03-12",
      "title": "[BUG] Unable to retrieve media file from URL in development",
      "issue_url": "https://github.com/vitalik/django-ninja/issues/1417",
      "comment_url": "https://github.com/vitalik/django-ninja/issues/1417#issuecomment-2718084512"
    }
  },
  {
    "model": "activities.activity",
    "pk": 2,
    "fields": {
      "created_on": "2025-03-12",
      "title": "[BUG] Data is not present on GET request after successful POST request.",
      "issue_url": "https://github.com/vitalik/django-ninja/issues/1411",
      "comment_url": "https://github.com/vitalik/django-ninja/issues/1411#issuecomment-2718203368"
    }
  },
  {
    "model": "activities.activity",
    "pk": 3,
    "fields": {
      "created_on": "2025-01-24",
      "title": "listing git files failed on git repo",
      "issue_url": "https://github.com/pypa/setuptools-scm/issues/997",
      "comment_url": "https://github.com/pypa/setuptools-scm/issues/997#issuecomment-2612367874"
    }
  },
  {
    "model": "activities.activity",
    "pk": 4,
    "fields": {
      "created_on": "2022-03-04",
      "title": "optional argument --bootstrap with value no install djangocms-bootstrap4",
      "issue_url": "https://github.com/nephila/djangocms-installer/issues/392",
      "comment_url": "https://github.com/nephila/djangocms-installer/issues/392#issue-1159976979"
    }
  },
  {
    "model": "activities.activity",
    "pk": 5,
    "fields": {
      "created_on": "2022-03-03",
      "title": "[BUG]",
      "issue_url": "https://github.com/django-cms/django-cms/issues/7258",
      "comment_url": "https://github.com/django-cms/django-cms/issues/7258#issue-1158454914"
    }
  },
  {
    "model": "activities.activity",
    "pk": 6,
    "fields": {
      "created_on": "2018-10-10",
      "title": "GLIBC_2.27 not supported",
      "issue_url": "https://github.com/atom/atom/issues/18170",
      "comment_url": "https://github.com/atom/atom/issues/18170#issuecomment-445811418"
    }
  },
  {
    "model": "activities.activity",
    "pk": 7,
    "fields": {
      "created_on": "2018-05-01",
      "title": "Curl https issue ssl3_get_record when behind proxy",
      "issue_url": "https://github.com/curl/curl/issues/2324",
      "comment_url": "https://github.com/curl/curl/issues/2324#issuecomment-385668085"
    }
  },
  {
    "model": "activities.activity",
    "pk": 8,
    "fields": {
      "created_on": "2016-09-20",
      "title": "\"login with google\" silently fails, no login occurs",
      "issue_url": "https://github.com/pypi/legacy/issues/492",
      "comment_url": "https://github.com/pypi/legacy/issues/492#issuecomment-248241815"
    }
  }
]
